name: Deploy Content to USXSecMonitoringv2 [c0872e5e-557d-4490-9f6b-958cf9caa905]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-c0872e5e-557d-4490-9f6b-958cf9caa905.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main-sentinel-deployment ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-c0872e5e-557d-4490-9f6b-958cf9caa905.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'USXSecOpsv2'
      workspaceName: 'USXSecMonitoringv2'
      workspaceId: 'd3bc01da-2d55-4c5b-9927-ee33b2483e05'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'Playbook'
      branch: 'main-sentinel-deployment'
      sourceControlId: 'c0872e5e-557d-4490-9f6b-958cf9caa905'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_c0872e5e557d44909f6b958cf9caa905 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_c0872e5e557d44909f6b958cf9caa905 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_c0872e5e557d44909f6b958cf9caa905 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_c0872e5e557d44909f6b958cf9caa905 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_c0872e5e557d44909f6b958cf9caa905 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_c0872e5e557d44909f6b958cf9caa905 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_c0872e5e557d44909f6b958cf9caa905 }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_c0872e5e557d44909f6b958cf9caa905 }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_c0872e5e557d44909f6b958cf9caa905 }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-c0872e5e-557d-4490-9f6b-958cf9caa905.ps1